server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: 18601

micro-breakpoint:
  database: ../python-debugger/data/debugger.sqlite3
  payload-root:
  settings-file: ../python-debugger/data/settings.json
  breakpoint-timeout-seconds: 300
